baseURL: "https://pandac.in/"
title: PandaC
pagination:
  paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Chittaranjan Panda's personal page"
  keywords: [Blog, Portfolio, Resume, Personal, Website, PANDAC, Chittaranjan Panda, Panda IND, Panda C, Chittaranjan, Panda]
  author: PandaC
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light, auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShareButtons: ["linkedin", "twitter"]
  searchHidden: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favico/favicon.ico"
    favicon16x16: "/img/favico/favicon-16x16.png"
    favicon32x32: "/img/favico/favicon-32x32.png"

#  label:
#    text: "Panda IND"
#    icon: /img/logo.svg
#    iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   # title: 
  #   # subtitle: "Coding Specialist, Multi-Platform Developer"
  #   imageUrl: "/img/pandac.png"
  #   imageWidth: 420
  #   imageHeight: 400
  #   imageTitle: pandac
  #   buttons:
  #     - name: Resume
  #       url: /resume/
      # - name: Projects
        # url: /projects/
#      - name: Tags
#        url: tags

  homeInfoParams:
    Title: Hi 👋, I'm Chittaranjan
    Content: A full-stack developer who loves turning real-world problems into simple, effective solutions. I care about writing clean, scalable code and have a strong passion for AI, cloud tech, and building smarter, more reliable software.


  socialIcons:
    - name: email
      url: "mailto:connect@pandac.in"
    - name: github
      url: "https://github.com/pandaind"
    - name: linkedin
      url: "https://linkedin.com/in/pandac"
    - name: twitter
      url: "https://twitter.com/pandadebug"
    # - name: medium
      # url: "https://medium.com/@pandaind"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blogs
      name: Blogs
      url: /blogs/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    # - identifier: projects
      # name: Projects
      # url: /projects/
      # weight: 50
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    # - identifier: archive
      # name: Archive
      # url: /archives/
      # weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
