baseURL: "https://panda.ind.in/"
title: PandaIND
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Chittaranjan Panda's personal blog"
  keywords: [Blog, Portfolio, Resume, Personal, Website, Chittaranjan Panda, PandaIND, Chittaranjan, Panda]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShareButtons: ["linkedin", "twitter"]
  searchHidden: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/logo.svg"
    favicon16x16: "/img/logo.svg"
    favicon32x32: "/img/logo.svg"

#  label:
#    text: "PandaIND"
#    icon: /img/logo.svg
#    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Chittaranjan Panda
    subtitle: "Software Engineer, Full Stack Developer, Open Source Enthusiast"
    imageUrl: "/img/profile.jpg"
    imageWidth: 390
    imageHeight: 350
    imageTitle: my image
    buttons:
      - name: Resume
        url: https://docs.google.com/document/d/17B7XV9IqSzkT_iu9xAB_FVX-kI8vRx5h
#      - name: Tags
#        url: tags

  socialIcons:
    - name: email
      url: "mailto:info@panda.consulting"
    - name: github
      url: "https://github.com/pandaind"
    - name: linkedin
      url: "https://linkedin.com/in/pandaind"
    - name: twitter
      url: "https://twitter.com/_expertpanda"
    - name: medium
      url: "https://medium.com/@pandaind"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary